# fly.toml app configuration file generated for writing-buddy on 2023-05-02T06:15:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "writing-buddy"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "flyio/hellofly:latest"

[env]
  PRIMARY_REGION = "bos"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
